--RENOMBRAR ENTIDADES
RENAME EJEMPLO TO EJEMPLOS;

--RENOMBRAR CAMPOS
ALTER TABLE EJEMPLOS
RENAME COLUMN NOBRE TO NOMBRE;

--AGREGAR UN CAMPO A UNA ENTIDAD
ALTER TABLE EJEMPLOS
ADD APELLIDO VARCHAR2(100);

--ELIMINAR UN CAMPO A UNA ENTIDAD
ALTER TABLE EJEMPLOS
DROP COLUMN APELLIDO;

--BORRAR ENTIDADES
DROP TABLE USUARIOS ON CASCADE;

--FORMATOS
--ESTABLECER EL ANCHO DE LINEAS DE CONSOLA
SET LINE 210
--ESTABLECER FORMATO POR COLUMNA
COLUMN CONSTRAINT_NAME FORMAT A50
COLUMN CONSTRAINT_TYPE FORMAT A50
COLUMN SEARCH_CONDITION FORMAT A50

--ENCENDER MONITOR PLS/SQL
SET VERIFY OFF 
SET SERVEROUTPUT ON

--VER LOS CONSTRAINTS
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS;


--CREACIÓN DE TABLAS
CREATE TABLE USUARIOS(
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
USUARIO VARCHAR2(100),
CORREO VARCHAR2(200),
CONTRASENIA VARCHAR2(40),
NOMBRE VARCHAR2(100),
APELLIDO_PATERNO VARCHAR2(100),
APELLIDO_MATERNO VARCHAR2(100),
FECHA_NACIMIENTO DATE DEFAULT(SYSDATE),
GENERO VARCHAR2(1),--H(HOMBRE), M(MUJER), N(NO BINARIO) Y O(OTRO)
TELEFONO VARCHAR2(20),--+52-729-765-4321 (FRONT END VALIDA ESPACIOS BLANCOS CON -)
DIRECCION VARCHAR2(255),
CIUDAD VARCHAR2(60),
ESTADO VARCHAR2(60),
PAIS VARCHAR2(60),
CODIGO_POSTAL VARCHAR2(20),
IMAGEN_PERFIL CLOB, --GUARDA EL URL DE LA IMAGÉN DE PERFIL 'https://www.ejemplo.com'
FECHA_REGISTRO DATE DEFAULT(SYSDATE),
ROL_USUARIO VARCHAR2(1)--A(ADMINISTRADOR), V(VENDEDOR), C(CLIENTE) 
);

--CONSTRAINTS
--NOT NULL
ALTER TABLE USUARIOS
MODIFY USUARIO NOT NULL;

ALTER TABLE USUARIOS
MODIFY CORREO NOT NULL;

ALTER TABLE USUARIOS
MODIFY CONTRASENIA NOT NULL;

ALTER TABLE USUARIOS
MODIFY NOMBRE NOT NULL;

ALTER TABLE USUARIOS
MODIFY APELLIDO_PATERNO NOT NULL;

ALTER TABLE USUARIOS
MODIFY APELLIDO_MATERNO NOT NULL;

ALTER TABLE USUARIOS
MODIFY FECHA_NACIMIENTO NOT NULL;

ALTER TABLE USUARIOS
MODIFY GENERO NOT NULL;

ALTER TABLE USUARIOS
MODIFY TELEFONO NOT NULL;

ALTER TABLE USUARIOS
MODIFY DIRECCION NOT NULL;

ALTER TABLE USUARIOS
MODIFY CIUDAD NOT NULL;

ALTER TABLE USUARIOS
MODIFY ESTADO NOT NULL;

ALTER TABLE USUARIOS
MODIFY PAIS NOT NULL;

ALTER TABLE USUARIOS
MODIFY CODIGO_POSTAL NOT NULL;

ALTER TABLE USUARIOS
MODIFY IMAGEN_PERFIL NOT NULL;

ALTER TABLE USUARIOS
MODIFY FECHA_REGISTRO NOT NULL;

ALTER TABLE USUARIOS
MODIFY ROL_USUARIO NOT NULL;

--CHECK
ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_GENERO_CK CHECK(GENERO ='H' OR GENERO ='M' OR GENERO ='N' OR GENERO ='O');

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_ROL_USUARIO_CK CHECK(ROL_USUARIO ='A' OR ROL_USUARIO ='V' OR ROL_USUARIO ='C');

--UNIQUE
ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_USUARIO_UK UNIQUE(USUARIO);

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_CORREO_UK UNIQUE(CORREO);

--LLENADO TABLA
INSERT INTO USUARIOS (USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_REGISTRO, ROL_USUARIO) VALUES ('JONATHAN._.MP', 'L20280711@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT, 'A');
INSERT INTO USUARIOS (ID, USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_REGISTRO, ROL_USUARIO) VALUES (DEFAULT ,'JONATHAN._.MP', 'L20280711@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT, 'A');
