--RENOMBRAR ENTIDADES
RENAME EJEMPLO TO EJEMPLOS;

--RENOMBRAR CAMPOS
ALTER TABLE EJEMPLOS
RENAME COLUMN NOBRE TO NOMBRE;

--AGREGAR UN CAMPO A UNA ENTIDAD
ALTER TABLE EJEMPLOS
ADD APELLIDO VARCHAR2(100);

--ELIMINAR UN CAMPO A UNA ENTIDAD
ALTER TABLE EJEMPLOS
DROP COLUMN APELLIDO;

--FORMATOS
--ESTABLECER EL ANCHO DE LINEAS DE CONSOLA
SET LINE 210
--ESTABLECER FORMATO POR COLUMNA
COLUMN CONSTRAINT_NAME FORMAT A40
COLUMN CONSTRAINT_TYPE FORMAT A40
COLUMN SEARCH_CONDITION FORMAT A40

--ENCENDER MONITOR PLS/SQL
SET VERIFY OFF 
SET SERVEROUTPUT ON

--VER LOS CONSTRAINTS
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS;

--CREO USUARIO
CONN SYS/ORACLE AS SYSDBA
--POR SI ES QUE YA LO TENIAMOS
DROP USER HOUSEVAK CASCADE;

CREATE USER HOUSEVAK IDENTIFIED BY PASS123;

GRANT ALL PRIVILEGES TO HOUSEVAK;

CONN HOUSEVAK/PASS123

--BORRAR ENTIDADES
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE AGENTES CASCADE CONSTRAINTS;
DROP TABLE PROPIEDADES CASCADE CONSTRAINTS;

--CREACIÓN DE TABLAS
CREATE TABLE USUARIOS(
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
USUARIO VARCHAR2(100),
CORREO VARCHAR2(200),
CONTRASENIA VARCHAR2(40),
NOMBRE VARCHAR2(100),
APELLIDO_PATERNO VARCHAR2(100),
APELLIDO_MATERNO VARCHAR2(100),
FECHA_NACIMIENTO DATE DEFAULT(SYSDATE),
GENERO VARCHAR2(1),--H(HOMBRE), M(MUJER), N(NO BINARIO) Y O(OTRO)
TELEFONO VARCHAR2(20),--+52-729-765-4321 (FRONT END VALIDA ESPACIOS BLANCOS CON -)
DIRECCION VARCHAR2(255),
CIUDAD VARCHAR2(60),
ESTADO VARCHAR2(60),
PAIS VARCHAR2(60),
CODIGO_POSTAL VARCHAR2(20),
IMAGEN_PERFIL CLOB, --GUARDA EL URL DE LA IMAGÉN DE PERFIL 'https://www.ejemplo.com'
FECHA_REGISTRO DATE DEFAULT(SYSDATE)
);

CREATE TABLE AGENTES(
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
USUARIO VARCHAR2(100),
CORREO VARCHAR2(200),
CONTRASENIA VARCHAR2(40),
NOMBRE VARCHAR2(100),
APELLIDO_PATERNO VARCHAR2(100),
APELLIDO_MATERNO VARCHAR2(100),
FECHA_NACIMIENTO DATE DEFAULT(SYSDATE),
GENERO VARCHAR2(1),--H(HOMBRE), M(MUJER) Y O(OTRO)
TELEFONO VARCHAR2(20),--+52-729-765-4321 (FRONT END VALIDA ESPACIOS BLANCOS CON -)
DIRECCION VARCHAR2(255),
CIUDAD VARCHAR2(60),
ESTADO VARCHAR2(60),
PAIS VARCHAR2(60),
CODIGO_POSTAL VARCHAR2(20),
IMAGEN_PERFIL CLOB, --GUARDA EL URL DE LA IMAGÉN DE PERFIL 'https://www.ejemplo.com'
FECHA_CONTRATACION DATE DEFAULT(SYSDATE),
SALARIO NUMBER,
PORCENTAJE_COMISION NUMBER(2,2)
);

CREATE TABLE PROPIEDADES(
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_AGENTE NUMBER, --LLAVE FORANEA DE UN USUARIO
  ID_VENDEDOR NUMBER, -- LLAVE FORANEA DE UN USUARIO
  ID_COMPRADOR NUMBER, --LLAVE FORANEA DE UN USUARIO (PUEDE SER NULA)
  TITULO VARCHAR2(255),
  DESCRIPCION CLOB,
  TIPO_PROPIEDAD VARCHAR2(15), -- CASA / DEPARTAMENTO
  PRECIO NUMBER(11,2),
  NUM_HABITACIONES NUMBER(2),
  NUM_BANIOS NUMBER(2),
  SUPERFICIE NUMBER(8,2),--METROS CUADRADOS
  DIRECCION VARCHAR2(255),
  CIUDAD VARCHAR2(60),
  ESTADO VARCHAR2(60),
  PAIS VARCHAR2(60),
  CODIGO_POSTAL VARCHAR2(20),
  IMAGEN_PRINCIPAL CLOB,
  IMAGENES_ADICIONALES CLOB,
  FECHA_PUBLICACION DATE DEFAULT(SYSDATE),
  ESTADO_PROPIEDAD VARCHAR2(1), -- V (venta), R (renta)
  DISPONIBLE VARCHAR2(1) -- S(si), N(no)
);


--CONSTRAINTS
--LLAVES FORANEAS
ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_ID_AGENTE_FK FOREIGN KEY (ID_AGENTE)
REFERENCES AGENTES(ID);

ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_ID_VENDEDOR_FK FOREIGN KEY (ID_VENDEDOR)
REFERENCES USUARIOS(ID);

ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_ID_COMPRADOR_FK FOREIGN KEY (ID_COMPRADOR)
REFERENCES USUARIOS(ID);

--NOT NULL
--USUARIOS
ALTER TABLE USUARIOS
MODIFY USUARIO NOT NULL;

ALTER TABLE USUARIOS
MODIFY CORREO NOT NULL;

ALTER TABLE USUARIOS
MODIFY CONTRASENIA NOT NULL;

ALTER TABLE USUARIOS
MODIFY NOMBRE NOT NULL;

ALTER TABLE USUARIOS
MODIFY APELLIDO_PATERNO NOT NULL;

ALTER TABLE USUARIOS
MODIFY APELLIDO_MATERNO NOT NULL;

ALTER TABLE USUARIOS
MODIFY FECHA_NACIMIENTO NOT NULL;

ALTER TABLE USUARIOS
MODIFY GENERO NOT NULL;

ALTER TABLE USUARIOS
MODIFY TELEFONO NOT NULL;

ALTER TABLE USUARIOS
MODIFY DIRECCION NOT NULL;

ALTER TABLE USUARIOS
MODIFY CIUDAD NOT NULL;

ALTER TABLE USUARIOS
MODIFY ESTADO NOT NULL;

ALTER TABLE USUARIOS
MODIFY PAIS NOT NULL;

ALTER TABLE USUARIOS
MODIFY CODIGO_POSTAL NOT NULL;

ALTER TABLE USUARIOS
MODIFY IMAGEN_PERFIL NOT NULL;

ALTER TABLE USUARIOS
MODIFY FECHA_REGISTRO NOT NULL;

--AGENTES
ALTER TABLE AGENTES
MODIFY USUARIO NOT NULL;

ALTER TABLE AGENTES
MODIFY CORREO NOT NULL;

ALTER TABLE AGENTES
MODIFY CONTRASENIA NOT NULL;

ALTER TABLE AGENTES
MODIFY NOMBRE NOT NULL;

ALTER TABLE AGENTES
MODIFY APELLIDO_PATERNO NOT NULL;

ALTER TABLE AGENTES
MODIFY APELLIDO_MATERNO NOT NULL;

ALTER TABLE AGENTES
MODIFY FECHA_NACIMIENTO NOT NULL;

ALTER TABLE AGENTES
MODIFY GENERO NOT NULL;

ALTER TABLE AGENTES
MODIFY TELEFONO NOT NULL;

ALTER TABLE AGENTES
MODIFY DIRECCION NOT NULL;

ALTER TABLE AGENTES
MODIFY CIUDAD NOT NULL;

ALTER TABLE AGENTES
MODIFY ESTADO NOT NULL;

ALTER TABLE AGENTES
MODIFY PAIS NOT NULL;

ALTER TABLE AGENTES
MODIFY CODIGO_POSTAL NOT NULL;

ALTER TABLE AGENTES
MODIFY IMAGEN_PERFIL NOT NULL;

ALTER TABLE AGENTES
MODIFY FECHA_CONTRATACION NOT NULL;

ALTER TABLE AGENTES
MODIFY SALARIO NOT NULL;

ALTER TABLE AGENTES
MODIFY PORCENTAJE_COMISION NOT NULL;

--PROPIEDADES
ALTER TABLE PROPIEDADES
MODIFY ID_AGENTE NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY ID_VENDEDOR NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY TITULO NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY DESCRIPCION NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY TIPO_PROPIEDAD NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY PRECIO NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY NUM_HABITACIONES NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY NUM_BANIOS NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY SUPERFICIE NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY DIRECCION NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY CIUDAD NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY ESTADO NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY PAIS NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY CODIGO_POSTAL NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY IMAGEN_PRINCIPAL NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY IMAGENES_ADICIONALES NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY FECHA_PUBLICACION NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY ESTADO_PROPIEDAD NOT NULL;

ALTER TABLE PROPIEDADES
MODIFY DISPONIBLE NOT NULL;

------------------------------------------------------------------------------------

--CHECK
--USUARIOS
ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_GENERO_CK CHECK(GENERO ='H' OR GENERO ='M' OR GENERO ='O');

--AGENTES
ALTER TABLE AGENTES
ADD CONSTRAINT AGENTES_GENERO_CK CHECK(GENERO ='H' OR GENERO ='M' OR GENERO ='O');

--PROPIEDADES
ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_TIPO_PROPIEDAD_CK CHECK(TIPO_PROPIEDAD ='CASA' OR TIPO_PROPIEDAD ='DEPARTAMENTO');

ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_ESTADO_PROPIEDAD_CK CHECK(ESTADO_PROPIEDAD ='V' OR ESTADO_PROPIEDAD ='R');

ALTER TABLE PROPIEDADES
ADD CONSTRAINT PROPIEDADES_DISPONIBLE_PROPIEDAD_CK CHECK(DISPONIBLE ='S' OR DISPONIBLE ='N');


--UNIQUE
--USUARIOS
ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_USUARIO_UK UNIQUE(USUARIO);

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_CORREO_UK UNIQUE(CORREO);

--AGENTES
ALTER TABLE AGENTES
ADD CONSTRAINT AGENTES_USUARIO_UK UNIQUE(USUARIO);

ALTER TABLE AGENTES
ADD CONSTRAINT AGENTES_CORREO_UK UNIQUE(CORREO);

--LLENADO TABLA USUARIOS
INSERT INTO USUARIOS (USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_REGISTRO) VALUES ('JONATHAN._.MP', 'L20280711@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT);
INSERT INTO USUARIOS (USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_REGISTRO) VALUES ('JONATHAN._.MP_1', 'L20280712@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT);

--LLENADO TABLA AGENTES
INSERT INTO AGENTES (USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_CONTRATACION, SALARIO, PORCENTAJE_COMISION) VALUES ('ADMIN_JONATHAN._.MP', 'A20280711@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT, 10.12, .10);
INSERT INTO AGENTES (USUARIO, CORREO, CONTRASENIA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PERFIL, FECHA_CONTRATACION, SALARIO, PORCENTAJE_COMISION) VALUES ('ADMIN_JONATHAN._.MP_1', 'A20280712@TOLUCA.TECNM.MX', '1q2W3E4R5t6', 'JONATHAN', 'MONTALVO', 'PÉREZ', '09/08/02', 'H', '+52-729-765-4321', 'Av Tecnológico 100-s/n, AGRÍCOLA', 'METEPEC', 'ESTADO DE MÉXICO', 'MÉXICO', '52149','https://drive.google.com/file/d/1ANXZ8gXBpGxKbxpzQiMqyfXzWlMZEdNl/view?usp=share_link', DEFAULT,10.13, .13);

--LLENADO TABLA PROPIEDADES
INSERT INTO PROPIEDADES (ID_AGENTE, ID_VENDEDOR, ID_COMPRADOR, TITULO, DESCRIPCION, TIPO_PROPIEDAD, PRECIO, NUM_HABITACIONES, NUM_BANIOS, SUPERFICIE, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PRINCIPAL, IMAGENES_ADICIONALES, ESTADO_PROPIEDAD, DISPONIBLE) VALUES (1, 2, NULL,'TÍTULO DE LA PROPIEDAD', 'DESCRIPCIÓN DE LA PROPIEDAD', 'CASA', 1000000.00, 4, 3, 200.00,'DIRECCIÓN DE LA PROPIEDAD', 'CIUDAD DE LA PROPIEDAD', 'ESTADO DE LA PROPIEDAD', 'PAÍS DE LA PROPIEDAD', '52149', 'IMAGEN PRINCIPAL DE LA PROPIEDAD', 'IMÁGENES ADICIONALES DE LA PROPIEDAD', 'V', 'S');
UPDATE PROPIEDADES SET ID_COMPRADOR = 2 WHERE ID = 1;

INSERT INTO PROPIEDADES (ID_AGENTE, ID_VENDEDOR, ID_COMPRADOR, TITULO, DESCRIPCION, TIPO_PROPIEDAD, PRECIO, NUM_HABITACIONES, NUM_BANIOS, SUPERFICIE, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PRINCIPAL, IMAGENES_ADICIONALES, ESTADO_PROPIEDAD, DISPONIBLE) VALUES (1, 2, NULL,'TÍTULO DE LA PROPIEDAD', 'DESCRIPCIÓN DE LA PROPIEDAD', 'CASA', 1000000.00, 4, 3, 200.00,'DIRECCIÓN DE LA PROPIEDAD', 'CIUDAD DE LA PROPIEDAD', 'ESTADO DE LA PROPIEDAD', 'PAÍS DE LA PROPIEDAD', '52149', 'IMAGEN PRINCIPAL DE LA PROPIEDAD', 'IMÁGENES ADICIONALES DE LA PROPIEDAD', 'V', 'S');
UPDATE PROPIEDADES SET ID_COMPRADOR = 1 WHERE ID = 2;

INSERT INTO PROPIEDADES (ID_AGENTE, ID_VENDEDOR, ID_COMPRADOR, TITULO, DESCRIPCION, TIPO_PROPIEDAD, PRECIO, NUM_HABITACIONES, NUM_BANIOS, SUPERFICIE, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PRINCIPAL, IMAGENES_ADICIONALES, ESTADO_PROPIEDAD, DISPONIBLE) VALUES (1, NULL, NULL,'TÍTULO DE LA PROPIEDAD', 'DESCRIPCIÓN DE LA PROPIEDAD', 'CASA', 1000000.00, 4, 3, 200.00,'DIRECCIÓN DE LA PROPIEDAD', 'CIUDAD DE LA PROPIEDAD', 'ESTADO DE LA PROPIEDAD', 'PAÍS DE LA PROPIEDAD', '52149', 'IMAGEN PRINCIPAL DE LA PROPIEDAD', 'IMÁGENES ADICIONALES DE LA PROPIEDAD', 'V', 'S');
INSERT INTO PROPIEDADES (ID_AGENTE, ID_VENDEDOR, ID_COMPRADOR, TITULO, DESCRIPCION, TIPO_PROPIEDAD, PRECIO, NUM_HABITACIONES, NUM_BANIOS, SUPERFICIE, DIRECCION, CIUDAD, ESTADO, PAIS, CODIGO_POSTAL, IMAGEN_PRINCIPAL, IMAGENES_ADICIONALES, ESTADO_PROPIEDAD, DISPONIBLE) VALUES (NULL, NULL, NULL,'TÍTULO DE LA PROPIEDAD', 'DESCRIPCIÓN DE LA PROPIEDAD', 'CASA', 1000000.00, 4, 3, 200.00,'DIRECCIÓN DE LA PROPIEDAD', 'CIUDAD DE LA PROPIEDAD', 'ESTADO DE LA PROPIEDAD', 'PAÍS DE LA PROPIEDAD', '52149', 'IMAGEN PRINCIPAL DE LA PROPIEDAD', 'IMÁGENES ADICIONALES DE LA PROPIEDAD', 'V', 'S');

COMMIT;

SET LINE 180
COLUMN TITULO FORMAT A30
COLUMN USUARIO FORMAT A30
COLUMN CORREO FORMAT A30
COLUMN TITULO FORMAT A30
HOST CLS

SELECT ID, ID_AGENTE, ID_VENDEDOR, ID_COMPRADOR, TITULO
FROM PROPIEDADES;

SELECT ID, USUARIO, CORREO
FROM USUARIOS;

SELECT ID, USUARIO, CORREO, SALARIO, PORCENTAJE_COMISION
FROM AGENTES;
